import { StyleSheet } from "react-native";

export const gameStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    padding: 12,
    gap: 8,
    alignItems: "stretch",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    gap: 12,
  },
  recoveryText: {
    textAlign: "center",
  },
  box: {
    borderWidth: 1,
    padding: 8,
    alignSelf: "stretch",
  },
  assetsHousingButton: {
    padding: 12,
    alignSelf: "stretch",
    backgroundColor: "#f3f3f4",
  },
  assetsBrowsePropertiesButton: {
    padding: 12,
    alignSelf: "stretch",
    backgroundColor: "#f3f3f4",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    alignSelf: "stretch",
  },
  profileButton: {
    width: "60%",
    padding: 12,
    minHeight: 84,
    justifyContent: "center",
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
  },
  profileButtonExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  profileButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileButtonNameGroup: {
    flex: 1,
    justifyContent: "center",
  },
  profileButtonTitle: {
    fontSize: 20,
    lineHeight: 26,
  },
  ageYearBox: {
    minWidth: 120,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
  },
  ageYearSeasonGroup: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  ageYearSeasonIcon: {
    width: 28,
    height: 28,
  },
  ageYearSeasonText: {
    textAlign: "center",
  },
  ageYearInfoGroup: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
  },
  ageYearAgeText: {
    fontSize: 18,
    lineHeight: 24,
  },
  ageYearText: {
    fontSize: 15,
    lineHeight: 20,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "stretch",
    gap: 12,
  },
  tileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignSelf: "stretch",
    gap: 8,
  },
  tileButton: {
    width: "31%",
    aspectRatio: 1,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  tileButtonText: {
    textAlign: "center",
  },
  innerBox: {
    borderWidth: 1,
    padding: 8,
    marginTop: 8,
  },
  familyItem: {
    marginTop: 8,
  },
  detailBox: {
    borderWidth: 1,
    padding: 12,
    gap: 8,
    marginTop: 8,
  },
  detailGroup: {
    gap: 8,
  },
  houseCardContainer: {
    marginTop: 8,
  },
  houseCard: {
    padding: 12,
    backgroundColor: "#f3f3f4",
    gap: 8,
  },
  houseCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  houseDetailBox: {
    padding: 12,
    gap: 8,
    marginTop: -8,
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: 14,
  },
  browseActionCard: {
    padding: 12,
    backgroundColor: "#f3f3f4",
    alignSelf: "stretch",
  },
  tbcActionText: {
    color: "#b42318",
  },
  propertyListingCard: {
    borderWidth: 1,
    padding: 12,
    gap: 8,
    backgroundColor: "#ffffff",
  },
  propertyListingPlaceholder: {
    width: "100%",
    aspectRatio: 1.25,
    borderWidth: 1,
    backgroundColor: "#f3f3f4",
  },
  partnerCardContainer: {
    marginTop: 8,
  },
  partnerCard: {
    padding: 8,
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
    gap: 10,
  },
  partnerCardExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  partnerDetailBox: {
    padding: 12,
    gap: 8,
    marginTop: -8,
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: 14,
  },
  partnerEngineeringButton: {
    position: "absolute",
    top: 12,
    right: 12,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
    zIndex: 1,
  },
  partnerActionsButton: {
    marginTop: 8,
    alignSelf: "stretch",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f3f3f4",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#b8bcc4",
  },
  partnerActionsButtonExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  partnerActionsButtonText: {
    fontSize: 15,
    lineHeight: 19,
  },
  partnerConflictButtonText: {
    color: "#b42318",
  },
  partnerActionsMenu: {
    padding: 12,
    gap: 8,
    marginTop: -1,
    backgroundColor: "#f3f3f4",
    borderWidth: 1,
    borderColor: "#b8bcc4",
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  partnerMenuActionButton: {
    alignSelf: "stretch",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f3f3f4",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#b8bcc4",
  },
  partnerSubmenu: {
    gap: 8,
    paddingLeft: 12,
  },
  playerDetailsCard: {
    backgroundColor: "#f3f3f4",
    borderRadius: 18,
    borderWidth: 0,
    borderTopLeftRadius: 0,
    marginTop: 8,
    paddingTop: 14,
  },
  profileDetailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  profileHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileStatLine: {
    flex: 1,
  },
  familyDetailHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  familyRelationshipBarWrap: {
    flex: 1,
  },
  familyEngineeringButton: {
    position: "absolute",
    top: 0,
    right: 0,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
    zIndex: 1,
  },
  familyInfoLabel: {
    fontSize: 15,
    lineHeight: 20,
  },
  profileInfoLabel: {
    fontSize: 15,
    lineHeight: 20,
  },
  profileInfoValue: {
    fontSize: 16,
    lineHeight: 22,
  },
  jobsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  questionButton: {
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  testingText: {
    color: "#808080",
  },
  engineeringHeader: {
    alignSelf: "stretch",
    gap: 8,
  },
  screenHeader: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerBackButton: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  appScreenHeader: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
  },
  discoverHeaderRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
  },
  headerSideButton: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 72,
    alignItems: "center",
  },
  headerSideSpacer: {
    minWidth: 72,
  },
  appScreenHeaderTitleWrap: {
    flex: 1,
    alignItems: "center",
  },
  discoverRoseBadge: {
    minWidth: 72,
    alignItems: "flex-end",
  },
  screenTitle: {
    fontSize: 24,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    alignSelf: "stretch",
  },
  progressLine: {
    flex: 1,
    borderBottomWidth: 1,
  },
  progressStepActive: {},
  sectionTitle: {
    fontSize: 22,
  },
  fieldSectionTitle: {
    fontSize: 18,
  },
  profileIconBox: {
    alignSelf: "center",
    width: 120,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  playerProfilePhotoFrame: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#f3f3f4",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  playerProfilePhotoPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#f3f3f4",
    flexShrink: 0,
  },
  playerProfilePhoto: {
    width: 48,
    height: 48,
  },
  profilePhotoFrame: {
    alignSelf: "center",
    width: 120,
    height: 120,
    borderRadius: 28,
    backgroundColor: "#f3f3f4",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profilePhotoPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 28,
    backgroundColor: "#f3f3f4",
  },
  profilePhoto: {
    width: 120,
    height: 120,
  },
  profileIconHead: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 22,
  },
  profileIconBody: {
    width: 80,
    height: 52,
    borderWidth: 1,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  readOnlyFieldGroup: {
    borderWidth: 1,
    alignSelf: "stretch",
  },
  readOnlyFieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
  },
  readOnlyFieldRowLast: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
  },
  ageSelectorsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "stretch",
  },
  selectedOptionBox: {
    borderWidth: 2,
  },
  disabledOptionBox: {
    opacity: 0.5,
  },
  sliderRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  sliderStep: {
    minWidth: 36,
    paddingHorizontal: 6,
    paddingVertical: 8,
    borderWidth: 1,
    alignItems: "center",
  },
  sliderStepActive: {
    borderWidth: 2,
  },
  sliderStepLabel: {
    fontSize: 12,
  },
  ageSelectorsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "stretch",
    gap: 16,
  },
  ageSelector: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  ageAdjustButton: {
    borderWidth: 1,
    minWidth: 48,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  discoverTitleRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  matchesHeadingRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  detailGroupRight: {
    alignItems: "flex-end",
  },
  engineerToggleButton: {
    borderWidth: 1,
    minWidth: 40,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  discoverProfileHeader: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    marginBottom: 12,
  },
  smallProfileIconBox: {
    width: 56,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  smallProfileIconHead: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderRadius: 12,
  },
  smallProfileIconBody: {
    width: 40,
    height: 28,
    borderWidth: 1,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  matchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  matchRowContent: {
    flex: 1,
    gap: 4,
  },
  matchDetailsActionGrid: {
    alignSelf: "stretch",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  matchDetailsActionButton: {
    width: "48%",
    borderWidth: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  discoverActionRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: 8,
  },
  discoverActionButton: {
    flex: 1,
    borderWidth: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  genderOptionRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    gap: 8,
  },
  genderOption: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  engineeringTitle: {
    fontSize: 24,
  },
  engineeringTabRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignSelf: "stretch",
  },
  engineeringTab: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  engineeringTabActive: {
    backgroundColor: "#111111",
  },
  engineeringTabText: {
    color: "#000000",
  },
  engineeringTabActiveText: {
    color: "#ffffff",
  },
  engineeringButton: {
    position: "absolute",
    left: 84,
    bottom: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#111111",
    alignItems: "center",
    justifyContent: "center",
  },
  engineeringButtonText: {
    color: "#ffffff",
    fontSize: 11,
  },
  tbcButton: {
    position: "absolute",
    right: 88,
    bottom: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#1e6bff",
    alignItems: "center",
    justifyContent: "center",
  },
  tbcButtonText: {
    color: "#ffffff",
  },
  testButton: {
    position: "absolute",
    left: 16,
    bottom: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#1f9d55",
    alignItems: "center",
    justifyContent: "center",
  },
  testButtonText: {
    color: "#ffffff",
  },
  ageUpButton: {
    position: "absolute",
    bottom: 16,
    alignSelf: "center",
    minWidth: 92,
    borderWidth: 1,
    paddingVertical: 14,
    paddingHorizontal: 18,
    backgroundColor: "#ffffff",
  },
  ageUpButtonText: {
    color: "#000000",
    textAlign: "center",
  },
  versionBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#ffffff",
  },
  versionText: {
    color: "#000000",
    fontSize: 11,
  },
  tbcPanel: {
    position: "absolute",
    right: 88,
    bottom: 84,
    left: 16,
    borderWidth: 1,
    padding: 12,
    backgroundColor: "#ffffff",
    gap: 8,
  },
  tbcText: {
    color: "#000000",
  },
  ideasButton: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#d9d9d9",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasButtonText: {
    color: "#000000",
    fontSize: 11,
  },
  ideasPanel: {
    position: "absolute",
    right: 16,
    bottom: 84,
    left: 16,
    borderWidth: 1,
    padding: 12,
    backgroundColor: "#ffffff",
    gap: 8,
  },
});

export type GameStyles = typeof gameStyles;
